# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup, find_packages
except ImportError:
    from distutils.core import setup

with open('README.md') as readme_file:
        readme = readme_file.read()

setup(
    author="Artem Viktorov",
    author_email='aviktorov12@gmail.com',
    long_description=readme,
    name='financial_manager',
    version='1.2.0',
    packages=find_packages(where="src/", exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    package_dir={"": "src"},
    include_package_data=True,
    package_data={"src": ["migrations/*", "migrations/versions/*"]},
    data_files=[('', ['template.env', 'src/alembic.ini', 'scripts/alembic_migration_helper.sh'])],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.11',
    ]
)
