"""union_income_outcome_to_transactions

Revision ID: ac2845977f5f
Revises: fb6814798e01
Create Date: 2025-02-07 12:43:49.381619+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac2845977f5f"
down_revision = "fb6814798e01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("transaction_date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("money_sum", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uid"], ["users.uid"], name=op.f("fk_transactions_user_uid_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_transactions")),
    )
    op.drop_table("outcomes")
    op.drop_table("incomes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incomes",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("income_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("money_sum", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_uid"], ["users.uid"], name="fk_incomes_user_uid_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid", name="pk_incomes"),
    )
    op.create_table(
        "outcomes",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("income_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("money_sum", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_uid"], ["users.uid"], name="fk_outcomes_user_uid_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid", name="pk_outcomes"),
    )
    op.drop_table("transactions")
    # ### end Alembic commands ###
