"""create_tables

Revision ID: fb6814798e01
Revises:
Create Date: 2025-02-03 20:22:53.241617+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb6814798e01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Commands auto generated by Alembic - please adjust!"""
    op.create_table(
        "users",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_users")),
    )
    op.create_table(
        "categories",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("money_sum", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uid"], ["users.uid"], name=op.f("fk_categories_user_uid_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_categories")),
        sa.UniqueConstraint("user_uid", "name", name="categories_uc"),
    )
    op.create_table(
        "incomes",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("income_date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("money_sum", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uid"], ["users.uid"], name=op.f("fk_incomes_user_uid_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_incomes")),
    )
    op.create_table(
        "outcomes",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("income_date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("money_sum", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uid"], ["users.uid"], name=op.f("fk_outcomes_user_uid_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_outcomes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Commands auto generated by Alembic - please adjust!"""
    op.drop_table("outcomes")
    op.drop_table("incomes")
    op.drop_table("categories")
    op.drop_table("users")
    # ### end Alembic commands ###
