triggers:
- build-success:
    description: run deploy master stand
tasks:
- clean
- checkout:
    force-clean-build: 'true'
    description: Checkout Default Repository
- inject-variables: 'bamboo-vars/.env-common'
- inject-variables: !include 'tasks/inject-vars-release.yml'
- inject-variables: !include 'tasks/inject-vars-master.yml'
- inject-variables: !include 'tasks/inject-vars-rc.yml'
- scp: !include 'tasks/deploy_ci_env-scp.yml'
- ssh: !include 'tasks/deploy_deb_ssh_with_envs.yml'
final-tasks: []
variables: {}
requirements: []
notifications:
- events:
  - deployment-failed
  recipients:
  - groups:
    - acm-admins
  - groups:
    - acm-developers
