---
version: 2
plan:
  project-key: ACM
  key: APTY
  name: python-template
  description: Plan python-template
variables:
  artifactory_docker: acmp-docker.artifactory.astralinux.ru
  dh_virtualenv_image: dh_virtualenv:v1.2.2_2
  python_pip_image: python-pip:v3.7_6
  python_pip_req_services: python-pip-req-${bamboo.shortPlanName}:latest
  dind_docker_name: docker:dind_v5
  secret_password: BAMSCRT@0@0@1k2/00Bqw5Ed6RBaUKWOYPocASsFTByJP3up1020qR709+HOlF1QylI5Q7LwqoknFhuiiJacFTdaS0Emqh6oifyhneT8Z2C71NRq4u5u6kw=
  secret_username: BAMSCRT@0@0@R8DmTyh6yJuzYbXsTCeHKw==
  secretYCSApriv: BAMSCRT@0@0@RcUGNZm7j2MsCTbNbmvzHU6xDUPEu+F0zxal8o68FyW2wjeyD6RAs+BUApNbS5atBo+WCWENFAXdK29ZfZP6IVaNqYxdU5emOBv79kNvn+VAqzJtj38t5BzBY2smeBxFEqEfTApV/IlMOQMTbDQI6IqbxfCjzSpzUoTVAyGL+rsQZQ6292yO2H1ZtpdMgek/cuwfWe5STbNljzojG1MwWwCJbjzo0xsiHnVpFPJ/6FOyDBdDmWGfuhu3o6NvEHfgBd6mnnE0r30kabqcQT/RnMpfYWsf58/6IeBO4XWYAcPhCA4OuJF5haGAQr2Aonbfi6+bJx4EjOORmqx9XrdpN4ZxO14XKBptizB+2i7VqqQDKdGk5xxqAHjbmCZYEwTjgk/K6sByb3KuBMO0ROFaogJ2VZthXuGjvD/VaiPZH7j2004WGPfVlJg0GiuHyF3QlJcgGE6/d42bJGHzrZA1heJIEM7DmeZLffgco+gXb1TmOJ/cUDPM959QJLnO5EF2EbHx3b0f0CAHZESOIIMKAqyAPr9uZJugZDVXpY227gpdkfmwNl4Hk6Zl0/hqJwd6HxziFQSoCaBEOpEKNOae4EiWNKJoiUl/tYG9lHnu2Nm+8M7Bt9TxwAwuzMW2+af9odi5U/rrSnmPUhkoCe5shsUwpc6I5+x96KeRAXx0x9PtdsU7zCPJz0JFDEcGsg88xWMgRXpKeHRhgkzBNSeffwZPCieHJjnfkPDAgTMGcpZdG3ZBBn/btuw5o5jhpLDfTw+4jKBbIX6XDuczcx9LuA/MNxCdD3jzZw4dqo9SsFJk2EOgeZU20L6WpUPpnsyyzzcN4YdS7qED8geu2tGBuDHBmFNhbxhaxyycay3KbLdBU7cxEHT/+9CjMiJu7OPWonXYFBgYWvGocCWGbGb96csdjGopHJigTHwxad/IxGUJ5m0ZS99/BxiBFHKXiJSb8hEYhmlJh8bK+TBCV5Y33BLQMGXjx9QXLxcpmmwCsoqW400VzPIxNrMf8x+kyXN3zpAl6UaZN3vDQgjpEqJO5dd+HQAu9XtuqjkSomA2xNG8R0urfdxLXjVGKB/P5JxtkcA+PJ+dr1KzDUuzzKdgFgPx93HJ9dNX7ZS5u+bqSZvOn9cWvcTqWyTbfBXVCtIKQOK39H2fOChZYc9RSi6/QWnEgCibkBX7Ul/9CI6NNCEf4r0CpHHfrYfcfGiIbDWA97kbzkY0HMdMwK5ZlgeAp62D4FpGJidQKkJK99eLlGS7oxEz3SVoKwi3BWFvztd1pFAxi45FvAUjkvMjjo/O5JwrTSIhQfNf2HUGpSYBaflPT47tYwPtRUiTpDfRMyxm7AjoR8l5y2XEs22EZxE7PYxM9/vdn3OzqqL3I2Hj+vnueqIFDDp4PCsGEPJY1n10t5TLWF/PYw8UaAYlaC672c7pOiT3aLVxBxLunjVwyhYEGwgAC9DcEeES5tlXHYj34SrlN8/eriXWxV56qJPs3KImBgD+YOuSq/fpthxN+uYjluuwi3khrEZUiBq1+7ICNZqXk848nZDbmLBP9gQFyNdCMpEef8UFJQtvQiAuSJo1v4A9ocFFAZjlvaSwEjWUJjdXZnELFCODF+G5n4dFSLc3Os/Pm/GXjluXBcm5ykqc1sJbwPk7XxiE5I4IjZOcaccYEdfIiIcUeWsScj+5ypRA5JiKwLqadAekaVuwuqiNfjNJ2zcQL8YlDlZQjtvX1iImQILmfCwWU6BmFWvRsdK5iYh9g+i+vuBOemNi4kSA9t6W9VMaYuDQ6htSosIV0ROG5gJ/r8iaXz7Xp+DIJvklfqE1foUXZpWMlKW4Dsp7IpMsjGVUw+b5Tw7B0/NpYIOG172y09n4C5v7E5/M+nM7LXxnA4Dif0Cx8OT/4N3Wp54zArqdQw5fXaHGE7zQZOAJi8pNQA7rhz1h0F9jd952HYeXfi7+qIdFBmIK6eXPZO/hNUUpPeItS7TINkpa6NL90VJmXOklwPPkEoA6Rv6ro5hf+9A7xix0T0Z7NL+kDe8jGpGfSh+mqjXnQtnhdx2vv88AwWrhlsrm4AFNdU1weqnPF0mKkzQePBQgrH/y+XfOrr/cjYRInrR/BsYY49bLjS+zXGuCTlHBzRI6wK1NEUMEvN4evorHP3HNNHO9VSHnlRK/d4QQ8RGA4qp4qBwpYy7z/xPQyrB6v/hhiYa6Nk7r2aJC3QkheGFZQe7hpANmkXMoHSbRjc54aWfdn0l1aFT8ttdtcT4TzSs3eCR1ZWdQzN5na2vSucKVsM0Owol2iYpIoNQqroCi7qOeJvw9Gbn30wrYQexphF5cYg==
  secretYCSApub: BAMSCRT@0@0@jmWoJHu6bcJnyw2VHFE81evGwdWuBmmRjbzqoTpTA10HbN3rYEpWlNk/C7nP9CHLUCVPNAiVJjIFtyyz4qNBudyF8qFskLclnHMrPKf0oZa18a+sjRLjk8F9ozpvT2hdMA8Dl9w/IixK6Lyahh3Xd4AUpIMfKofsOEuGkY+jE6tiK7Ey15A5ZxIVjUoBAbFTfTEtOPlnyzNzu4bOWUSgJ/Z1oB3EbKeXGfceQEY0bM2CrTF6MHPiUHBLulGi2uNHzjBp6WpTqn5x95Haq8k+cinjSWyPNrotXG3WK51O3v5EO8OPVoaFzPKQNWnatmJhhYenfvJmKCSYHcAESqPFzgm8cXQGC0Hmez34kQhkSmo0dIX+J5XRxIV3XLRszDTF4iAftvhwdee6aWFGyuwgqIGxn/PXRTle+tCGBo4Bq0u6wCTXEL7+8M0dXIVuLhTHjhct4iNA6IjfXvqcYPKZovJQ9lf4BVuyTuIR3yWpWXpNtQ2bX7hB+dIOoVwQP2DK7fR1i+TfjNQNxH6UExiUfxCCp/GjtW1V+Vz6AcLkBKKt4dE4u2S8nAO4W0VzE/9aSCfvowifQOvYkbEstI+RmxZvZeIJhKbqJ060SqB46y8=
stages:
- Requirements build stage:
    manual: false
    final: false
    jobs:
    - Reqs ser build job
- PyPi Stage:
    manual: false
    final: false
    jobs:
    - Fill pypi artifactory
- Default Stage:
    manual: false
    final: false
    jobs:
    - Build sanity check
    - Linting backend job
- Unit test Stage:
    manual: false
    final: false
    jobs:
    - Run unit tests
    - Run behave tests
- Publish Stage:
    manual: false
    final: false
    jobs:
    - Publish backend job
Reqs ser build job:
  !include 'jobs/reqs_ser_build_job.yml'
Fill pypi artifactory:
  !include 'jobs/fill_pypi_arti_job.yml'
Run unit tests:
  !include 'jobs/run_unit_tests.yml'
Run behave tests:
  !include 'jobs/run_behave_tests.yml'
Build sanity check:
  !include 'jobs/build_sanity_check.yml'
Linting backend job:
  !include 'jobs/lint_backend_job.yml'
Publish backend job:
  !include 'jobs/publish_backend_job.yml'
repositories:
- ACM python-template:
    scope: global
- acm-proto:
    scope: project
triggers:
  - bitbucket-server-trigger:
      repositories:
        - ACM python-template
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 3
    after-inactive-days: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
