version: 2
plan:
  project-key: ACM
  key: ADTE
  name: acm-adel
  description: adel-examples-3
stages:
- First Stage:
    manual: false
    final: false
    jobs:
    - First Job
First Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository
  artifact-subscriptions: []
repositories:
- ACM python-template:
    scope: global
triggers:
- bitbucket-server-trigger:
    repositories:
    - ACM python-template
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 3
    after-inactive-days: never
  integration:
    merge-from: master
    push-on-success: true
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
