gen_dev_requirements: ## Сгенерировать файл requirements.txt для разработки
	pip-compile requirements-dev.in --resolver=backtracking --no-header -o ../../requirements.txt

gen_requirements: ## Сгенерировать файл requirements.txt для разработки
	pip-compile requirements-dev.in --resolver=backtracking --no-header -o ../../requirements.txt
